# Generated by Django 4.2.7 on 2023-11-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='products_favorites',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
