# Generated by Django 4.2.7 on 2023-11-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_products_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='products_favorites',
            new_name='products_favorite',
        ),
    ]
