# Generated by Django 4.2.7 on 2023-11-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0004_rename_products_favorite_userprofile_products_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='products_favorites',
            field=models.ManyToManyField(related_name='product_favorite', to='products.product'),
        ),
    ]
