# Generated by Django 4.2.7 on 2023-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0005_alter_userprofile_products_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='products_favorites',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
