# Generated by Django 4.2.7 on 2023-11-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_userprofile_products_favorites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='favorite_products',
            new_name='products_favorites',
        ),
    ]
